root/etc/e-smith/templates/etc/fail2ban/jail.local/10sogo

I got an error when performing the nethserver-fail2ban-save event due to the lost quotation marks in 10sogo...

missed quotation marks added

---

root/etc/e-smith/db/configuration/migrate/Fail2BanMail

On old installation, the default notification mail was admin@<mydomain>.
Push the old default inside the CustomDestemail prop if mail notification is
enabled.
Related to PR #20

Migrate mail addresses for old installations

---

nethserver-fail2ban.spec
root/usr/libexec/nethserver/fail2ban-status
root/usr/libexec/nethserver/shorewall-nethserver
root/usr/share/nethesis/NethServer/Language/en/NethServer_Module_Dashboard_SystemStatus_Fail2ban.php
root/usr/share/nethesis/NethServer/Module/Dashboard/SystemStatus/Fail2ban.php
root/usr/share/nethesis/NethServer/Template/Dashboard/SystemStatus/Fail2ban.php

fail2ban logs the jail ban in a sqlite database which is reseted each time the service starts, I would like something we could monitor or store for ever
https://github.com/NethServer/dev/issues/5480

Permanent statistic of jail ban

---

root/usr/libexec/nethserver/shorewall-nethserver

https://github.com/NethServer/dev/issues/5503
die in fail2ban log if the ban or unban is impossible
if the counter of ban > 2, then the unban delete the esmith key and unban the IP

Fail2ban warn if ban/unban are impossible

---

root/etc/fail2ban/filter.d/postfix-sasl-abuse.conf

NethServer/dev/issues/5737
Also anchor regexp

postfix-sasl-abuse: catch usernames without @

---

nethserver-fail2ban.json

Respect new naming policy.
As requested by @DavidePrincipi  in NethServer/dev#5745

Remove 'NethServer' from name

---

root/etc/e-smith/templates/etc/fail2ban/jail.local/10asterisk

The asterisk jail by default is set to send email when a ban occurs, we want to decide if we send email or not
https://github.com/NethServer/dev/issues/5829

Overwrite the default action for the asterisk jail

---

root/etc/fail2ban/filter.d/asterisk_nethserver.conf

Reject anonymous sip connection
If we could check real server logs, maybe we could find more custom filters to add :-?
https://github.com/NethServer/dev/issues/5849

Asterisk custom filters

---

createlinks
root/etc/e-smith/events/actions/nethserver-fail2ban-cleanShorewallDynamic

With the move ipset for fail2ban, it possibly have some IP still banned in the dynamic zone of shorewall, we can release them safely, when fail2ban will restart, the logs will be inspected again and the relevant IP will be banned in ipset
https://github.com/NethServer/dev/issues/5943

Release all IP in shorewal dynamic

---

createlinks
nethserver-fail2ban.spec
root/etc/e-smith/templates/etc/fail2ban/jail.local/10recidive
root/etc/e-smith/templates/etc/shorewall/blrules/20fail2ban
root/etc/e-smith/templates/etc/shorewall/initdone/20fail2ban
root/etc/e-smith/templates/etc/shorewall/stopped/20fail2ban
root/usr/libexec/nethserver/fail2ban-ipset-destroy

https://github.com/NethServer/dev/issues/5943
we need to add a new script to destroy the ipset when shorewall stops, but `shorewall restart` does not exactly the same things than `systemctl restart shorewall`, IPSET complains that the set are still used by the kernel, so I need to use systemctl with `nethserver-fail2ban-save` when the sysadmin add or remove the jails.
Now we create the bantime with ipset on the fly, but we cannot have anymore a dynamic bantime for recidive because we are limited to `2147483` which is the maximum timeout of ipset. If you prefer we could set the recidive to the maximum, it is about 24 days

Fix fail2ban010

---

nethserver-fail2ban.spec
root/usr/bin/fail2ban-unban

https://github.com/NethServer/dev/issues/5943

Fail2ban-unban is a wrapper to unban

---

UI-API.md
api/read
createlinks
root/etc/e-smith/events/actions/nethserver-fail2ban-clean-sqlite-backup
root/etc/e-smith/templates/etc/fail2ban/fail2ban.local/10all

After a while we can find copy of sqlite database in /var/lib/fail2ban, this can take some rooms for several reasons
the goal of the PR is to clean the DB if we detect some copies of the db in `/var/lib/fail2ban`
```
-rw------- 1 root root 94635008 Jan 12  2020 fail2ban.sqlite3.20200112-212251
-rw------- 1 root root 39815168 Aug  3 16:27 fail2ban.sqlite3.20200803-142712
```
- remove the backup of the database
- set a static `DbPurgeage` to 1209600
https://github.com/NethServer/dev/issues/6285

Remove backup of fail2ban sqlite database

---

nethserver-fail2ban.spec
root/etc/cron.monthly/nethserver-fail2ban-vacuum

We can improve the size of the sqlite database by doing a vacuum each month. It can improve really the speed because fail2ban remove the ban inside the db but sqlite does not reclaim the space itself.
To test the PR you can lock the db by
` sqlite3 /var/lib/fail2ban/fail2ban.sqlite3`
to lock
`BEGIN EXCLUSIVE;`
to unlock
`COMMIT;`
then trigger the script : `/etc/cron.monthly/nethserver-fail2ban-vacuum`
https://github.com/NethServer/dev/issues/6291

Vacuum the sqlite database each month

---

root/etc/e-smith/templates/etc/fail2ban/jail.local/01localaccess

The former backend validation of IP  removes the CIDR network and writes an IP
```
-    use Net::IPv4Addr qw(ipv4_chkip);
-    push @ip, $iptest if $iptest = ipv4_chkip($ip);
+    push @ip, $ip;
```
1.2.3.0/24 => 1.2.3.4
we do not need anymore this validation I needed it before when I started without backend
https://github.com/NethServer/dev/issues/6301

Remove backend validation for IP

---

root/etc/e-smith/templates/etc/fail2ban/jail.local/10rspamd

Support rspamd UI running on port 443
See NethServer/nethserver-mail#230
Nethserver/dev#6320

rspamd: support jail for standard http port

---

root/etc/e-smith/templates/etc/fail2ban/jail.local/10rspamd

This reverts commit b55dca9a30b19dadcbf890b324538b5f94bbff6c.
NethServer/dev#6344
See also NethServer/nethserver-mail#133

Revert "rspamd: support jail for standard http port"

---

api/validate
createlinks
ui/public/i18n/language.json
ui/src/views/Settings.vue

Debug can create a lot of logs, one customers who used DEBUG during a while got 600GB of fail2ban logs. Moreover it could beak also the recidive and lock out the sysadmin.
We do not provide anymore DEBUG, if enabled we go back to  INFO
https://github.com/NethServer/dev/issues/6470

DEBUG loglevel is not provided anymore

---

lib/perl/NethServer/Fail2Ban.pm
root/etc/e-smith/templates/etc/fail2ban/jail.local/10webtop
root/etc/fail2ban/filter.d/webtop.conf

With The new version of webtop we have an authentication log, we can grep exactly the bad attempt
https://github.com/NethServer/dev/issues/6486

New fail2ban  filter for webtop 

---

api/validate
ui/public/i18n/language.json

We can accept FQDN/Domain name for whitelisting, when you do not have a static IP it can help you to not be locked out.
https://github.com/NethServer/dev/issues/6491

Accept FQDN for whitelist

---

ui/public/i18n/language.json

The whitelist field now accepts also FQDNs not only IPs.
NethServer/dev#6491

UI: improve whitelist label

---

root/etc/e-smith/templates/etc/shorewall/initdone/20fail2ban

If the ipset are not created, shorewall may fail at boot with:
```
shorewall[989]: WARNING: Ipset f2b-asterisk-tcp does not exist /etc/shorewall/blrules (line 30)
shorewall[989]: WARNING: Ipset f2b-asterisk-udp does not exist /etc/shorewall/blrules (line 31)
```
NethServer/dev#6608

shorewall: make sure asterisk ipset are ready

---

.github/workflows/make-rpms.yml

Introduce a GitHub Actions workflow to automate the building and publishing of RPM packages upon pushes and pull requests to the main branches.

Add GitHub Actions workflow for building and publishing RPMs

---

prep-sources

Revise the build script to enhance the process for building the NS7 UI and improve the tar command for packaging.

Update build script for NS7 UI
