root/etc/fail2ban/filter.d/dovecot-nethserver.conf

https://github.com/NethServer/dev/issues/5481

Regex correction for imap brute force attack

---

root/usr/bin/fail2ban-listban

https://github.com/NethServer/dev/issues/5480

Wording to reflect the counter reset after a service restart

---

README.md
README.rst

https://github.com/NethServer/dev/issues/5489

Create a README for developers

---

root/usr/share/nethesis/NethServer/Language/en/NethServer_Module_Dashboard_SystemStatus_Fail2ban.php

I think the new label is more clear :)

UI: better no_fail2ban_stat_label

---

root/usr/share/nethesis/NethServer/Template/Dashboard/SystemStatus/Fail2ban.php

https://github.com/NethServer/dev/issues/5508

Blank dashboard due to missing closing tag

---

root/etc/e-smith/templates/etc/fail2ban/jail.local/10Nginx
root/etc/e-smith/templates/etc/fail2ban/jail.local/10PamGeneric
root/etc/e-smith/templates/etc/fail2ban/jail.local/10apache
root/etc/e-smith/templates/etc/fail2ban/jail.local/10jabber
root/etc/e-smith/templates/etc/fail2ban/jail.local/10sshd

https://github.com/NethServer/dev/issues/5518

Avoid to configure a jail when the  log is missing

---

root/etc/e-smith/templates/etc/fail2ban/jail.local/10asterisk

Disable the asterisk jail following the asterisk service

---

root/usr/share/nethesis/NethServer/Module/Fail2BanStatus/Fail2BanUnban.php

https://github.com/NethServer/dev/issues/5546

Refresh the Unban page after the event

---

root/usr/libexec/nethserver/shorewall-nethserver

https://github.com/NethServer/dev/issues/5565

Move fail2ban database to a specific path

---

root/etc/e-smith/templates/etc/fail2ban/jail.local/05GlobalSettings
root/usr/share/nethesis/NethServer/Module/Fail2Ban/Fail2BanSettings.php

https://github.com/NethServer/dev/issues/5586
This intend to mail to root@$SystemName.$DomainName, root@$DomainName is not know by postfix configuration

Mail to root as default

---

root/etc/e-smith/templates/etc/fail2ban/jail.local/10roundcubemail

https://github.com/NethServer/dev/issues/5592

Use the relevant log for roundcubemail jail

---

root/etc/e-smith/templates/etc/fail2ban/jail.local/10Postfix

Rename Postfix_IgnoreIP to PostfixSaslAbuse_IgnoreIP

---

createlinks
root/etc/e-smith/events/actions/fail2ban-unban
root/etc/e-smith/events/actions/nethserver-fail2ban-unban-whitelist
root/usr/bin/fail2ban-listban
root/usr/bin/fail2ban-unban
root/usr/share/nethesis/NethServer/Module/Fail2BanStatus/Fail2BanUnban.php

-Indentation
-License
-Allow Whitelisted IP
-Remove the property usage and use parameters in nethgui
https://github.com/NethServer/dev/issues/5620

Unban development

---

root/etc/fail2ban/filter.d/rspamd.conf

https://github.com/NethServer/dev/issues/5663

Catch User login and modified URL

---

root/etc/e-smith/templates/etc/fail2ban/jail.local/10roundcubemail

https://github.com/NethServer/dev/issues/5693

Roundcubemail jail if  errors.log exists

---

root/etc/e-smith/templates/etc/fail2ban/jail.local/10asterisk
root/etc/fail2ban/filter.d/asterisk_nethserver.conf

https://github.com/NethServer/dev/issues/5703

Implement filter to protect asterisk manager interface (AMI)

---

root/usr/libexec/nethserver/shorewall-nethserver

https://github.com/NethServer/dev/issues/5759

Validation of the json storage file

---

root/etc/e-smith/events/actions/fail2ban-unban
root/etc/e-smith/events/actions/nethserver-fail2ban-unban-whitelist
root/usr/bin/fail2ban-unban

https://github.com/NethServer/dev/issues/5808

Use the wrapper shorewall-nethserver to unban

---

api/read
api/update
nethserver-fail2ban.spec
root/etc/sudoers.d/50_nsapi_nethserver_fail2ban

API delegation for nethserver-fail2ban
NethServer/dev#5805

CmndAlias api for cockpit delegation

---

ui/src/views/Settings.vue

BanLocalNetwork and Recidive_Perpetual was not saved with the good values
https://github.com/NethServer/dev/issues/5905

Fix recidive and banLocalNetwork saving properties

---

createlinks
root/etc/e-smith/templates/etc/fail2ban/jail.local/10recidive

Fix recidive perpetual with ipset

---

ui/public/i18n/language.json
ui/src/views/Jails.vue
ui/src/views/Settings.vue
ui/src/views/Unban.vue

Replaces #79 
https://github.com/NethServer/dev/issues/5943

UI: remove double enable/disable button, improve ban list page

---

root/usr/bin/fail2ban-unban

https://github.com/NethServer/dev/issues/5973

Added usage on fail2ban-unban

---

api/read
ui/package-lock.json
ui/package.json
ui/public/i18n/language.json
ui/src/filters/filters.js
ui/src/main.js
ui/src/views/Dashboard.vue

https://github.com/NethServer/dev/issues/5978

Display the time of the last statistics

---

ui/public/i18n/language.json
ui/src/App.vue

Updated dashboard title and app name.
Refer to https://github.com/NethServer/dev/issues/6004

ui. update dashboard title and app name

---

ui/package-lock.json
ui/package.json
ui/public/i18n/language.json
ui/src/views/Logs.vue

Improve fail2ban logs view and fix package vulnerabilites.
Refer to https://github.com/NethServer/dev/issues/6005

ui. improve logs view

---

createlinks

https://github.com/NethServer/dev/issues/6040

Restart shorewall before fail2ban for IPSET creation

---

api/update

https://github.com/NethServer/dev/issues/6044

Do no update status for jails case

---

root/etc/e-smith/events/actions/nethserver-fail2ban-shorewall-event
root/etc/e-smith/templates/etc/shorewall/initdone/20fail2ban
ui/public/i18n/language.json
ui/src/views/Settings.vue

https://github.com/NethServer/dev/issues/6071
- display an information banner on the usage of recidive perpetual
- Increase the hash file size for perpetual recidive

Increase the hash file size for perpetual recidive

---

root/etc/e-smith/templates/etc/shorewall/initdone/20fail2ban
ui/public/i18n/language.json

Revert hash size file 
display the maximum number of IP in recidive set
NethServer/dev#6071

Revert hash file size & display maxelem for f2b-recidive set

---

root/usr/libexec/nethserver/fail2ban-statistics

https://github.com/NethServer/dev/issues/6253

Add timout to avoid locked sqlite db

---

ui/public/i18n/language.json
ui/src/views/Jails.vue

- add translation for 'save' button
- improve labels for jails' page
NethServer/dev#6265

ui: improve labels

---

README.rst

Removed the obsolete json database

---

root/usr/share/nethesis/NethServer/Help/en/NethServer_Module_Fail2Ban.rst

https://github.com/NethServer/dev/issues/6265

Incremental ban time for nethgui help

---

root/etc/e-smith/events/actions/nethserver-fail2ban-clean-sqlite-backup

https://github.com/NethServer/dev/issues/6285

Protect the Find pattern against Bash "Pattern matching" expansion

---

api/validate
ui/public/i18n/language.json
ui/src/views/Settings.vue

We provide a way to whitelist IP in fail2ban, we could also provide te whitelist for network. 
0.0.0.0/0 is prohibited. 
https://github.com/NethServer/dev/issues/6301

Whitelist networks in Fail2ban

---

ui/src/views/Dashboard.vue

before the list of jail is displayed on the bottom of the piechart
the PR display the list of jails on the side of the piechart

Display widgets with row (side by side)

---

ui/src/views/About.vue

UI: honor manifest links

---

root/etc/e-smith/templates/etc/shorewall/blrules/20fail2ban

asterisk jail use 
```
Name: f2b-asterisk-tcp
Name: f2b-asterisk-udp
```
NethServer/dev#6605

Use specific ipset for asterisk jail 
